server:
  port: 7000
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: test

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# jackson 字符串转日期全局格式
  jackson:
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/

mybatis-plus:
  type-aliases-package: com.ratel.hydra.**.po
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty


logging:
  level:
    com.ratel.hydra.system.mapper: debug
    root: info